fix(tenants): fix AttributeError if specify an intermediary model
Error log:

AttributeError: Cannot use add() on a ManyToManyField which
specifies an intermediary model...

If manually specify the intermediary model for the ManyToManyField
in the Tenant model, it will lead to AttributeError cause Django
does not save custom many-to-many relationships.

"Unlike normal many-to-many fields, you can’t use add(), create(),
or set() to create relationships."

Check this URL for details:

https://docs.djangoproject.com/en/2.1/topics/db/models/#intermediary-manytomany